version: '3.8'

services:
  app:
    build: .
    container_name: agriculture_assistant_app
    ports:
      - "8004:8004"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - APIFY_API_TOKEN=${APIFY_API_TOKEN}  # Add APIFY_API_TOKEN here
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
